qiniu:
  accessKey: "PrDqAGnMOoRreKCW3pspNgkg7Cd6FFhmqoAkNb-D"
  secretKey: "AfbDjGLm3dswOqwufzzIzeq31gWAKu3FmO5ZJsX4"
  bucket: "gulimall233"

spring:
  application:
    name: gulimall-third-party

  cloud:
    nacos:
      discovery:
        server-addr: 192.168.119.135:8848
server:
  port: 30000